junit:
  stage: test
  script:
    - mvn -B clean test

generate_artifacts:
  stage: deploy
  script:
    - mvn -B clean site package
#    - mvn -B clean package
    - tar -czf target/site.tar.gz target/site
  artifacts:
    paths:
      - gameX/racemodel/target/racemodel*.jar
      - gameX/visualiser/target/visualiser*.jar
      - target/site.tar.gz