junit:
  stage: test
  script:
    - mvn -B clean test

generate_artifacts:
  stage: deploy
  script:
    - mvn -B clean site package

generate_artifacts_test:
  stage: deploy
  script:
    - mvn -B clean site package
  artifacts:
    paths:
      - racevision/*/target/*.jar
  only:
    - modularisation